print(0)
b = instantiate("button")
print(1)
add(b)
print(2)
setProperty(b, "x", 100)
print(3)
setProperty(b, "y", 100)
print(4)
setProperty(b, "text", "djfdf")
print(5)

x = getProperty(b, "x")
print(x)
y = getProperty(b, "y")
print(y)
text = getProperty(b, "text")
print(text)